const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('public/index.html','utf8'),js=fs.readFileSync('public/assets/js/script.js','utf8'),css=fs.readFileSync('public/assets/css/style.css','utf8');
assert.match(html,/<title>Web Fleet<\/title>/);
assert.match(html,/data-instance-launcher/);
assert.match(html,/data-product="webfleet"/);
assert.match(html,/data-instance-grid/);
assert.match(html,/data-open-config/);
assert.match(html,/data-instance-form/);
assert.match(html,/name="name"/);
assert.match(html,/<th>Name<\/th>/);
assert.match(html,/data-instance-modal/);
assert.match(html,/data-add-instance/);
assert.match(html,/Port <span class="optional">\(optional\)<\/span>/);
assert.match(html,/data-instance-table/);
assert.match(html,/data-delete-selected/);
assert.match(html,/data-import/);
assert.match(html,/data-export/);
assert.match(html,/data-import-file/);
assert.match(html,/data-status/);
assert.match(html,/data-select-page/);
assert.match(html,/data-page-input/);
assert.match(js,/instances-v1/);
assert.ok(js.includes("DEFAULT_LOCAL_URL='http://localhost:7336/'"));
assert.match(js,/nameValue/);
assert.match(js,/name:n,domain:d,port:p\|\|null/);
assert.match(js,/\$\{esc\(item.name\)\}<\/strong>/);
assert.match(js,/displayEndpoint\(item\)/);
assert.match(js,/instances.length===0/);
assert.match(js,/instances.length===0\)location\.replace\(DEFAULT_LOCAL_URL\)/);
assert.match(js,/instances.length===1/);
assert.match(js,/location.replace\(endpoint\(instances\[0\]\)\)/);
assert.match(js,/LAUNCH_PAGE_SIZE=6,CONFIG_PAGE_SIZE=10/);
assert.match(js,/crypto.randomUUID/);
assert.match(js,/CONFIG_VERSION=1/);
assert.match(js,/instances\.json/);
assert.match(js,/application\/json/);
assert.match(js,/file\.text\(\)/);
assert.match(js,/normalizeImport/);
assert.match(js,/version:CONFIG_VERSION,product,instances/);
assert.match(js,/name:item\.name,domain:item\.domain/);
assert.match(js,/item\.port\?\{port:item\.port\}/);
assert.match(js,/Replace all/);
assert.match(js,/Delete \${selected.size} \${selected.size===1\?'instance'\:'instances'}/);
assert.match(js,/openModal/);
assert.match(js,/data-add-instance/);
assert.doesNotMatch(js,/-host`|-local-port|watchpost-main-host/);
assert.match(css,/\.form-grid\{display:grid;grid-template-columns:1fr;gap:12px\}/);
console.log('Web Fleet instance launcher contracts passed');
