const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('public/index.html','utf8'),js=fs.readFileSync('public/assets/js/script.js','utf8');
assert.match(html,/<title>Web Fleet<\/title>/);
assert.match(html,/data-instance-launcher/);
assert.match(html,/data-product="webfleet"/);
assert.match(html,/data-instance-grid/);
assert.match(html,/data-open-config/);
assert.match(html,/data-instance-form/);
assert.match(html,/name="name"/);
assert.match(html,/<th>Name<\/th>/);
assert.match(html,/data-instance-modal/);
assert.match(html,/data-add-instance/);
assert.match(html,/Port <span class="optional">\(optional\)<\/span>/);
assert.match(html,/data-instance-table/);
assert.match(html,/data-delete-selected/);
assert.match(html,/data-select-page/);
assert.match(html,/data-page-input/);
assert.match(js,/instances-v1/);
assert.match(js,/nameValue/);
assert.match(js,/name:n,domain:d,port:p\|\|null/);
assert.match(js,/\$\{esc\(item.name\)\}<\/strong>/);
assert.match(js,/displayEndpoint\(item\)/);
assert.match(js,/instances.length===0/);
assert.match(js,/instances.length===1/);
assert.match(js,/location.replace\(endpoint\(instances\[0\]\)\)/);
assert.match(js,/LAUNCH_PAGE_SIZE=6,CONFIG_PAGE_SIZE=10/);
assert.match(js,/crypto.randomUUID/);
assert.match(js,/Delete \${selected.size} \${selected.size===1\?'instance'\:'instances'}/);
assert.match(js,/openModal/);
assert.match(js,/data-add-instance/);
assert.doesNotMatch(js,/-host`|-local-port|watchpost-main-host/);
console.log('Web Fleet instance launcher contracts passed');
